/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as SellerRouteRouteImport } from './routes/seller/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as SellerProductsRouteImport } from './routes/seller/products'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerCommentsRouteImport } from './routes/seller/comments'
import { Route as SellerAddProductRouteImport } from './routes/seller/addProduct'
import { Route as AuthUserSignupRouteImport } from './routes/auth/userSignup'
import { Route as AuthSellerSignupRouteImport } from './routes/auth/SellerSignup'
import { Route as SellerProductProductIdRouteImport } from './routes/seller/product/$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRouteRoute = SellerRouteRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerCommentsRoute = SellerCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerAddProductRoute = SellerAddProductRouteImport.update({
  id: '/addProduct',
  path: '/addProduct',
  getParentRoute: () => SellerRouteRoute,
} as any)
const AuthUserSignupRoute = AuthUserSignupRouteImport.update({
  id: '/auth/userSignup',
  path: '/auth/userSignup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSellerSignupRoute = AuthSellerSignupRouteImport.update({
  id: '/auth/SellerSignup',
  path: '/auth/SellerSignup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductProductIdRoute = SellerProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => SellerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/comments': typeof SellerCommentsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/': typeof SellerIndexRoute
  '/user/': typeof UserIndexRoute
  '/seller/product/$productId': typeof SellerProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/comments': typeof SellerCommentsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller': typeof SellerIndexRoute
  '/user': typeof UserIndexRoute
  '/seller/product/$productId': typeof SellerProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/comments': typeof SellerCommentsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/': typeof SellerIndexRoute
  '/user/': typeof UserIndexRoute
  '/seller/product/$productId': typeof SellerProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/seller'
    | '/user'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/comments'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/'
    | '/user/'
    | '/seller/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/comments'
    | '/seller/orders'
    | '/seller/products'
    | '/seller'
    | '/user'
    | '/seller/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/seller'
    | '/user'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/comments'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/'
    | '/user/'
    | '/seller/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SellerRouteRoute: typeof SellerRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthSellerSignupRoute: typeof AuthSellerSignupRoute
  AuthUserSignupRoute: typeof AuthUserSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/comments': {
      id: '/seller/comments'
      path: '/comments'
      fullPath: '/seller/comments'
      preLoaderRoute: typeof SellerCommentsRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/addProduct': {
      id: '/seller/addProduct'
      path: '/addProduct'
      fullPath: '/seller/addProduct'
      preLoaderRoute: typeof SellerAddProductRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/auth/userSignup': {
      id: '/auth/userSignup'
      path: '/auth/userSignup'
      fullPath: '/auth/userSignup'
      preLoaderRoute: typeof AuthUserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/SellerSignup': {
      id: '/auth/SellerSignup'
      path: '/auth/SellerSignup'
      fullPath: '/auth/SellerSignup'
      preLoaderRoute: typeof AuthSellerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/product/$productId': {
      id: '/seller/product/$productId'
      path: '/product/$productId'
      fullPath: '/seller/product/$productId'
      preLoaderRoute: typeof SellerProductProductIdRouteImport
      parentRoute: typeof SellerRouteRoute
    }
  }
}

interface SellerRouteRouteChildren {
  SellerAddProductRoute: typeof SellerAddProductRoute
  SellerCommentsRoute: typeof SellerCommentsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerProductProductIdRoute: typeof SellerProductProductIdRoute
}

const SellerRouteRouteChildren: SellerRouteRouteChildren = {
  SellerAddProductRoute: SellerAddProductRoute,
  SellerCommentsRoute: SellerCommentsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerProductProductIdRoute: SellerProductProductIdRoute,
}

const SellerRouteRouteWithChildren = SellerRouteRoute._addFileChildren(
  SellerRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SellerRouteRoute: SellerRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthSellerSignupRoute: AuthSellerSignupRoute,
  AuthUserSignupRoute: AuthUserSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
