/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as SellerRouteRouteImport } from './routes/seller/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as UserCartRouteImport } from './routes/user/cart'
import { Route as SellerReviewsRouteImport } from './routes/seller/reviews'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerAddProductRouteImport } from './routes/seller/addProduct'
import { Route as AuthUserSignupRouteImport } from './routes/auth/userSignup'
import { Route as AuthSellerSignupRouteImport } from './routes/auth/SellerSignup'
import { Route as SellerProductsIndexRouteImport } from './routes/seller/products/index'
import { Route as SellerProductsProductIdRouteImport } from './routes/seller/products/$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRouteRoute = SellerRouteRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const UserCartRoute = UserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => UserRouteRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerAddProductRoute = SellerAddProductRouteImport.update({
  id: '/addProduct',
  path: '/addProduct',
  getParentRoute: () => SellerRouteRoute,
} as any)
const AuthUserSignupRoute = AuthUserSignupRouteImport.update({
  id: '/auth/userSignup',
  path: '/auth/userSignup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSellerSignupRoute = AuthSellerSignupRouteImport.update({
  id: '/auth/SellerSignup',
  path: '/auth/SellerSignup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerProductsProductIdRoute = SellerProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => SellerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/user/cart': typeof UserCartRoute
  '/seller/': typeof SellerIndexRoute
  '/user/': typeof UserIndexRoute
  '/seller/products/$productId': typeof SellerProductsProductIdRoute
  '/seller/products': typeof SellerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/user/cart': typeof UserCartRoute
  '/seller': typeof SellerIndexRoute
  '/user': typeof UserIndexRoute
  '/seller/products/$productId': typeof SellerProductsProductIdRoute
  '/seller/products': typeof SellerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/SellerSignup': typeof AuthSellerSignupRoute
  '/auth/userSignup': typeof AuthUserSignupRoute
  '/seller/addProduct': typeof SellerAddProductRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/user/cart': typeof UserCartRoute
  '/seller/': typeof SellerIndexRoute
  '/user/': typeof UserIndexRoute
  '/seller/products/$productId': typeof SellerProductsProductIdRoute
  '/seller/products/': typeof SellerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/seller'
    | '/user'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/orders'
    | '/seller/reviews'
    | '/user/cart'
    | '/seller/'
    | '/user/'
    | '/seller/products/$productId'
    | '/seller/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/orders'
    | '/seller/reviews'
    | '/user/cart'
    | '/seller'
    | '/user'
    | '/seller/products/$productId'
    | '/seller/products'
  id:
    | '__root__'
    | '/'
    | '/seller'
    | '/user'
    | '/login'
    | '/auth/SellerSignup'
    | '/auth/userSignup'
    | '/seller/addProduct'
    | '/seller/orders'
    | '/seller/reviews'
    | '/user/cart'
    | '/seller/'
    | '/user/'
    | '/seller/products/$productId'
    | '/seller/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SellerRouteRoute: typeof SellerRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthSellerSignupRoute: typeof AuthSellerSignupRoute
  AuthUserSignupRoute: typeof AuthUserSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/user/cart': {
      id: '/user/cart'
      path: '/cart'
      fullPath: '/user/cart'
      preLoaderRoute: typeof UserCartRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/addProduct': {
      id: '/seller/addProduct'
      path: '/addProduct'
      fullPath: '/seller/addProduct'
      preLoaderRoute: typeof SellerAddProductRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/auth/userSignup': {
      id: '/auth/userSignup'
      path: '/auth/userSignup'
      fullPath: '/auth/userSignup'
      preLoaderRoute: typeof AuthUserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/SellerSignup': {
      id: '/auth/SellerSignup'
      path: '/auth/SellerSignup'
      fullPath: '/auth/SellerSignup'
      preLoaderRoute: typeof AuthSellerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/products/$productId': {
      id: '/seller/products/$productId'
      path: '/products/$productId'
      fullPath: '/seller/products/$productId'
      preLoaderRoute: typeof SellerProductsProductIdRouteImport
      parentRoute: typeof SellerRouteRoute
    }
  }
}

interface SellerRouteRouteChildren {
  SellerAddProductRoute: typeof SellerAddProductRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerProductsProductIdRoute: typeof SellerProductsProductIdRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
}

const SellerRouteRouteChildren: SellerRouteRouteChildren = {
  SellerAddProductRoute: SellerAddProductRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerProductsProductIdRoute: SellerProductsProductIdRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
}

const SellerRouteRouteWithChildren = SellerRouteRoute._addFileChildren(
  SellerRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserCartRoute: typeof UserCartRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserCartRoute: UserCartRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SellerRouteRoute: SellerRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthSellerSignupRoute: AuthSellerSignupRoute,
  AuthUserSignupRoute: AuthUserSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
